_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  bootstrap_styles: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  components: 0
  config: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  ebt_basic_button: 0
  ebt_core: 0
  ebt_cta: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  image: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  link: 0
  lunr: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_breadcrumb: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  sqlite: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  tome: 0
  tome_base: 0
  tome_static: 0
  tome_sync: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  radix: 0
  scatama: 0
profile: standard
